### ISSUE TITLE
rsocket can not run in browser

### ISSUE THREAD

**Issue by sheiy** [rsocket/rsocket-js#280] opened 2024-07-30 09:16 UTC
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/431e5e3b-910f-4cd7-b23d-703f8566ec77">

**Comment by sheiy** [comment] 2024-07-30 09:19
"rsocket-core": "^0.0.29-alpha.0",
    "rsocket-websocket-client": "^0.0.29-alpha.0"

**Comment by buchanancraig** [comment] 2024-07-31 15:30
this is also a problem in in 1.0.0-alpha.3 I've had to add it in a polyfill.ts

`import { Buffer } from 'buffer';

window.Buffer = Buffer;
`
from https://github.com/feross/buffer

but I still cannot get it working as I'm getting a "No handler for destination ''" warning and I'm not sure if it's a problem with the way the buffer is encoding the route.


actually, this is a duplicate of #267

**Comment by sheiy** [comment] 2024-08-01 09:10
@SoylentTheGreen Thanks for your reply. It looks like this project is not actively developed

**Closed as completed** 2024-08-01 09:10 UTC

**Comment by viglucci** [comment] 2024-08-02 01:44
Hey y'all, for `1.0.0-alpha.3` it is expected that you need to provide a buffer polyfill for usage in browser contexts. I'm not sure if simply setting `window.Buffer` is sufficient, however I've had success using webpack following methods such as this: https://viglucci.io/articles/how-to-polyfill-buffer-with-webpack-5. Additionally, there is an example showing a minimal setup using webpack to produce a bundle that runs in a Browser context. You can find that here: https://github.com/rsocket/rsocket-js/tree/1.0.x-alpha/packages/rsocket-examples/src/webpack/browser-bundle .

Apologies that I cannot speak much to the `0.0.X` versions.
