### ISSUE TITLE
How to get error response when websocket connection is failed to establish

### ISSUE THREAD

**Issue by akaskj** [rsocket/rsocket-js#91] opened 2020-07-07 22:29 UTC
I am using WSS transport with rsocket and when I configure the rsocket client and try to establish a connection. The connection request fails due to an expected error like authentication error or application authorization error. 

This message is not propagated to the application that is using the library. The only error message that can be seen in the error object is `RSocketClient: Connection closed.` 

However I see the WSS transport connection throwing the appropriate error message in the log.
`RSocketWebSocketClient.js:87 WebSocket connection to 'wss://{url}' failed: HTTP Authentication failed; no valid credentials available`

I also see the same error message in the network tab of the request.

But this is not available for the application to use.

Here is the code snippet on how I am opening the connection:

```
    rsocketClient = new RSocketClient({
      setup: {
        // ms btw sending keepalive to server
        keepAlive: WSS_RSOCKET_CLIENT_KEEP_ALIVE,
        // ms timeout if no keepalive response
        lifetime: WSS_RSOCKET_CLIENT_LIFETIME,
        dataMimeType: "application/json",
        metadataMimeType: "application/json"
      },
      responder: new WebEventsResponder()
    });

    rsocketClient._config.transport = new RSocketWebSocketClient({
      url: `${url}`,
      debug: true
    });
    rsocketclient.connect().subscribe({
      onComplete: rsocket => {
        resolve(rsocket);
      },
      onError: error => {
        console.log("---------error----------  " + error);
        reject(error);
      },
    });
```

Is there something I am doing wrong in the way I am handling the error? please let me know. This is critical for us to use rsocket in our system.

**Comment by OlegDokuka** [comment] 2021-01-25 20:42
duplicate of #106. @akaskj please see the following comment for more info https://github.com/rsocket/rsocket-js/issues/106#issuecomment-767063465.

In general, the websocket API provides only limited information in the `ErrorEvent`, therefore, we propagate only what is present there and can not the whole set of information.

**Closed** 2021-01-25 21:22 UTC
Labels: duplicate
